language: node_js

node_js:
   - 7
   - 6

branches:
  only:
    - master
    - dev

notifications:
    email: true

sudo: true

before_install:
    - yarn global add codecov

after_success:
    - codecov
